# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- task: 'UiPathRunJob@2'
  inputs:
    orchestratorConnection: 'Con_Orc_Devops'
    processName: 'Devops UI Integration'
    folderName: 'sowjanya adireddi'
    jobType: 'TestAutomation'
    user: 'sowjanya adireddy'

pool:
 Sowjanya 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
